.PHONY: all

all:
	$(MAKE) -f Makefile.inc X=   S=0 D=n all
#	$(MAKE) -f Makefile.inc X=g  S=0 D=y all
#	$(MAKE) -f Makefile.inc X=i  S=1 D=n all
#	$(MAKE) -f Makefile.inc X=ig S=1 D=y all

clean:
	$(MAKE) -f Makefile.inc X=   S=0 D=n clean
#	$(MAKE) -f Makefile.inc X=g  S=0 D=y clean
#	$(MAKE) -f Makefile.inc X=i  S=1 D=n clean
#	$(MAKE) -f Makefile.inc X=ig S=1 D=y clean

clean-nodist:
	$(MAKE) -f Makefile.inc X=   S=0 D=n clean
#	$(MAKE) -f Makefile.inc X=g  S=0 D=y clean-all
#	$(MAKE) -f Makefile.inc X=i  S=1 D=n clean-all
#	$(MAKE) -f Makefile.inc X=ig S=1 D=y clean-all

clean-all:
	$(MAKE) -f Makefile.inc X=   S=0 D=n clean-all
#	$(MAKE) -f Makefile.inc X=g  S=0 D=y clean-all
#	$(MAKE) -f Makefile.inc X=i  S=1 D=n clean-all
#	$(MAKE) -f Makefile.inc X=ig S=1 D=y clean-all

